# Generated by Django 4.2.7 on 2023-11-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='Telegram_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ник в тг'),
        ),
    ]
