# Generated by Django 4.2.7 on 2023-11-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('habit_type', models.CharField(choices=[('useful', 'Useful'), ('pleasant', 'Pleasant')], default='useful', max_length=8, verbose_name='Тип привычки')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('once_every_two_days', 'Once Every Two Days'), ('once_every_three_days', 'Once Every Three Days'), ('once_every_four_days', 'Once Every Four Days'), ('once_every_five_days', 'Once Every Five Days'), ('once_every_six_days', 'Once Every Six Days'), ('weekly', 'Weekly')], default='daily', max_length=21, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('duration', models.SmallIntegerField(verbose_name='Длительность выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_habits', models.ManyToManyField(blank=True, related_name='habits', to='main.habit', verbose_name='Связанные привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
